<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Korean Legislative Data for Researchers - The kna CLI: Master Database</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./images/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Korean Legislative Data for Researchers</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01-setup.html">1. Setup</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02-mcp.html">2. MCP + Claude</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03-python.html">3. Python</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04-r.html">4. R</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05-cases.html">5. Cases</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06-kna.html">6. kna CLI</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./07-voting.html">7. Voting</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./08-network.html">8. Networks</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./09-ideology.html">9. Ideology</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kyusik-yang/kna"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://national-assembly-kr.streamlit.app">Live Demo</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">The kna CLI: Master Database</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Korean Legislative Data for Researchers</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Getting Started</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-setup.html" class="sidebar-item-text sidebar-link">Chapter 1: Setup</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-mcp.html" class="sidebar-item-text sidebar-link">Chapter 2: MCP + Claude</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Scripting the API</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-python.html" class="sidebar-item-text sidebar-link">Chapter 3: Python</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-r.html" class="sidebar-item-text sidebar-link">Chapter 4: R</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Master Database &amp; CLI</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-kna.html" class="sidebar-item-text sidebar-link active">The kna CLI: Master Database</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Applied Research</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-cases.html" class="sidebar-item-text sidebar-link">Chapter 5: Research Cases</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-voting.html" class="sidebar-item-text sidebar-link">Voting Behavior &amp; Party Discipline</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-network.html" class="sidebar-item-text sidebar-link">Co-sponsorship Network Analysis</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-ideology.html" class="sidebar-item-text sidebar-link">Ideal Points &amp; Ideological Positioning</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#installation" id="toc-installation" class="nav-link" data-scroll-target="#installation">Installation</a>
  <ul class="collapse">
  <li><a href="#step-1-install-the-cli" id="toc-step-1-install-the-cli" class="nav-link" data-scroll-target="#step-1-install-the-cli">Step 1: Install the CLI</a></li>
  <li><a href="#step-2-get-the-data" id="toc-step-2-get-the-data" class="nav-link" data-scroll-target="#step-2-get-the-data">Step 2: Get the data</a></li>
  <li><a href="#step-3-point-the-cli-to-the-data" id="toc-step-3-point-the-cli-to-the-data" class="nav-link" data-scroll-target="#step-3-point-the-cli-to-the-data">Step 3: Point the CLI to the data</a></li>
  </ul></li>
  <li><a href="#quick-start" id="toc-quick-start" class="nav-link" data-scroll-target="#quick-start">Quick start</a>
  <ul class="collapse">
  <li><a href="#database-overview" id="toc-database-overview" class="nav-link" data-scroll-target="#database-overview">Database overview</a></li>
  <li><a href="#search-bills-by-title" id="toc-search-bills-by-title" class="nav-link" data-scroll-target="#search-bills-by-title">Search bills by title</a></li>
  <li><a href="#search-propose-reason-texts" id="toc-search-propose-reason-texts" class="nav-link" data-scroll-target="#search-propose-reason-texts">Search propose-reason texts</a></li>
  </ul></li>
  <li><a href="#bill-lifecycle-timeline" id="toc-bill-lifecycle-timeline" class="nav-link" data-scroll-target="#bill-lifecycle-timeline">Bill lifecycle timeline</a></li>
  <li><a href="#legislator-profiles" id="toc-legislator-profiles" class="nav-link" data-scroll-target="#legislator-profiles">Legislator profiles</a></li>
  <li><a href="#aggregate-statistics" id="toc-aggregate-statistics" class="nav-link" data-scroll-target="#aggregate-statistics">Aggregate statistics</a>
  <ul class="collapse">
  <li><a href="#legislative-funnel" id="toc-legislative-funnel" class="nav-link" data-scroll-target="#legislative-funnel">Legislative funnel</a></li>
  <li><a href="#passage-rate-trend" id="toc-passage-rate-trend" class="nav-link" data-scroll-target="#passage-rate-trend">Passage rate trend</a></li>
  </ul></li>
  <li><a href="#data-export" id="toc-data-export" class="nav-link" data-scroll-target="#data-export">Data export</a></li>
  <li><a href="#using-kna-data-in-python" id="toc-using-kna-data-in-python" class="nav-link" data-scroll-target="#using-kna-data-in-python">Using kna data in Python</a></li>
  <li><a href="#using-kna-data-in-r" id="toc-using-kna-data-in-r" class="nav-link" data-scroll-target="#using-kna-data-in-r">Using kna data in R</a></li>
  <li><a href="#command-reference" id="toc-command-reference" class="nav-link" data-scroll-target="#command-reference">Command reference</a></li>
  <li><a href="#companion-data" id="toc-companion-data" class="nav-link" data-scroll-target="#companion-data">Companion data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">The kna CLI: Master Database</h1>
<p class="subtitle lead">Query 115K bills, 2.6M votes, and ideal points from your terminal</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>The <code>kna</code> (Korean National Assembly) CLI provides offline, instant access to a <strong>pre-built master database</strong> that integrates 17 Open Assembly API endpoints into a single queryable interface. Unlike the live API (Chapters 3-4), <code>kna</code> works on processed Parquet files - no API key needed, no rate limits, no network latency.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
This chapter uses kna 0.7.0
</div>
</div>
<div class="callout-body-container callout-body">
<p>Chapters 6-9 use kna 0.7.0, whose data were collected from the Open Assembly API mostly on 2026-09-25. Release 0.7.0 corrects ten defects in the data shipped up to 0.6.0. Among them, the 17th-20th committee meeting tables stopped at five rows per bill, the roll-call votes of same-name legislators were dropped, party labels were the API’s current party applied to past votes, and cosponsorship edges stopped at 100 names per bill. The default ideal points changed, and <code>dw_ideal_points_20_22.csv</code> is no longer shipped. Before reusing results computed with earlier files, read the 2026-09-26 entry of <a href="https://github.com/kyusik-yang/kna/blob/main/CORRECTIONS.md">CORRECTIONS.md</a>.</p>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Live API (Ch 3-4)</th>
<th><strong>kna CLI</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bills</td>
<td>16-22nd (per query)</td>
<td><strong>17-22nd (115K pre-loaded, 67 columns in every assembly)</strong></td>
</tr>
<tr class="even">
<td>Lifecycle timestamps</td>
<td>Requires chaining 4+ endpoints</td>
<td><strong>Single row per bill, vetoes folded in</strong></td>
</tr>
<tr class="odd">
<td>Roll call votes</td>
<td>Per-bill, rate-limited</td>
<td><strong>2.6M member-level votes (20-22nd), instant</strong></td>
</tr>
<tr class="even">
<td>Member metadata</td>
<td>Per-query, current assembly only</td>
<td><strong>1,948 member-terms (17-22nd), with seniority at each assembly</strong></td>
</tr>
<tr class="odd">
<td>Cosponsorship</td>
<td>Per-bill, paginated</td>
<td><strong>1.38M bill-member rows (17-22nd), roles 대표발의 / 공동발의 / 찬성</strong></td>
</tr>
<tr class="even">
<td>Asset disclosures</td>
<td>Not available</td>
<td><strong>2,928 member-year wealth rows</strong></td>
</tr>
<tr class="odd">
<td>Ideal points</td>
<td>Not available</td>
<td><strong>940 legislator-terms (20-22nd), three series</strong></td>
</tr>
<tr class="even">
<td>Propose-reason texts</td>
<td>Not available</td>
<td><strong>60,925 bills (20-22nd)</strong></td>
</tr>
<tr class="odd">
<td>Speed</td>
<td>~2 req/sec</td>
<td><strong>Instant (local Parquet)</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="installation" class="level2">
<h2 class="anchored" data-anchor-id="installation">Installation</h2>
<section id="step-1-install-the-cli" class="level3">
<h3 class="anchored" data-anchor-id="step-1-install-the-cli">Step 1: Install the CLI</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install kna</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Or use <code>pipx install kna</code> which handles PATH automatically. This chapter needs version 0.7.0 or later, which <code>kna --version</code> reports.</p>
</section>
<section id="step-2-get-the-data" class="level3">
<h3 class="anchored" data-anchor-id="step-2-get-the-data">Step 2: Get the data</h3>
<p>The PyPI package contains the code only. The CLI needs processed Parquet data files hosted via <strong>Git LFS</strong>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install Git LFS (one-time)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="ex">brew</span> install git-lfs    <span class="co"># macOS</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># or: sudo apt install git-lfs    # Ubuntu/Debian</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> lfs install</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Clone with data</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/kyusik-yang/kna.git</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> kna</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you already cloned without LFS, parquet files will be tiny pointer files and <code>kna info</code> will fail. Fix with: <code>git lfs install &amp;&amp; git lfs pull</code></p>
</div>
</div>
</section>
<section id="step-3-point-the-cli-to-the-data" class="level3">
<h3 class="anchored" data-anchor-id="step-3-point-the-cli-to-the-data">Step 3: Point the CLI to the data</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">export</span> <span class="va">KBL_DATA</span><span class="op">=</span>~/kna/data/processed</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make it permanent</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">'export KBL_DATA="$HOME/kna/data/processed"'</span> <span class="op">&gt;&gt;</span> ~/.zshrc</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> ~/.zshrc</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> info</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="quick-start" class="level2">
<h2 class="anchored" data-anchor-id="quick-start">Quick start</h2>
<section id="database-overview" class="level3">
<h3 class="anchored" data-anchor-id="database-overview">Database overview</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> info</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>                    Korean National Assembly Database
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━┓
┃ Assembly           ┃    Bills ┃     Laws ┃  Enacted ┃ Promulg. ┃  Cols ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━┩
│ 17th (2004-08)     │    8,368 │    7,489 │    1,913 │    1,913 │    67 │
│ 18th (2008-12)     │   14,762 │   13,913 │    2,353 │    2,353 │    67 │
│ 19th (2012-16)     │   18,735 │   17,822 │    2,793 │    2,793 │    67 │
│ 20th (2016-20)     │   24,996 │   24,141 │    3,195 │    3,195 │    67 │
│ 21st (2020-24)     │   26,707 │   25,858 │    2,959 │    2,959 │    67 │
│ 22nd (2024-)       │   21,581 │   21,022 │    1,644 │    1,555 │    67 │
├────────────────────┼──────────┼──────────┼──────────┼──────────┼───────┤
│ Total              │  115,149 │  110,245 │   14,857 │   14,768 │       │
└────────────────────┴──────────┴──────────┴──────────┴──────────┴───────┘
  Laws = 법률안. Enacted = 법률안 원안가결 + 수정가결 (final result).
  Promulg. = 법률안 with a promulgation date (became law).

  Roll call votes    2,557,618  (20-22nd, member-level API votes)
  16-19th votes         41,281  (experimental, fragmentary; separate file)
  Ideal points             940  (20-22nd, bridged W-NOMINATE, v20260917)
  Members                1,948  (17-22nd, party/district/committee)
  Asset disclosures      2,928  (19-22nd, member-year wealth)
  Committee mtgs       818,448  (17-22nd)
  Bill texts            60,925  (20-22nd, propose-reason)
  Cosponsor edges    1,379,763  (17-22nd, 대표/공동발의 + 찬성)
  Subcommittee          93,981  (17-22nd, 소위 referrals/reviews)
  Alt. absorption       25,439  (17-22nd, 대안 -&gt; absorbed bills)
  Committee spells      13,616  (dated committee assignments)
  Vote tallies           8,611  (20-22nd, plenary tallies)
  Veto events               47  (17-22nd, 재의요구)
  Data freshness    2026-09-23</code></pre>
<p>The 16th-19th vote rows are parsed from plenary minutes. They are not a roll-call matrix, so kna keeps them in a separate experimental file and uses only the 20th-22nd API votes.</p>
</section>
<section id="search-bills-by-title" class="level3">
<h3 class="anchored" data-anchor-id="search-bills-by-title">Search bills by title</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keyword search</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> search <span class="st">"인공지능"</span> <span class="at">--assembly</span> 22</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine filters</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> search <span class="st">"부동산"</span> <span class="at">--assembly</span> 22 <span class="at">--status</span> enacted <span class="at">--committee</span> 국토</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># By proposer</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> search <span class="st">"조세특례제한법"</span> <span class="at">--proposer</span> 박범계 <span class="at">--assembly</span> 21 <span class="at">-n</span> 30</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Filter options:</strong></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>Description</th>
<th>Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>--assembly</code></td>
<td>Assembly number</td>
<td>17-22</td>
</tr>
<tr class="even">
<td><code>--committee</code></td>
<td>Committee name (partial match)</td>
<td>e.g.&nbsp;<code>과방</code>, <code>국토</code></td>
</tr>
<tr class="odd">
<td><code>--proposer</code></td>
<td>Lead proposer name (exact match, joint leads included)</td>
<td>e.g.&nbsp;<code>김영식</code></td>
</tr>
<tr class="even">
<td><code>--status</code></td>
<td>Status group</td>
<td><code>passed</code>, <code>enacted</code>, <code>reflected</code>, <code>pending</code>, <code>rejected</code>, <code>expired</code></td>
</tr>
<tr class="odd">
<td><code>--kind</code></td>
<td>Bill type</td>
<td><code>법률안</code>, <code>결의안</code>, <code>동의안</code></td>
</tr>
<tr class="even">
<td><code>--from</code> / <code>--to</code></td>
<td>Proposal date range</td>
<td>YYYY-MM-DD</td>
</tr>
<tr class="odd">
<td><code>-n</code></td>
<td>Max results (default 20)</td>
<td>integer</td>
</tr>
</tbody>
</table>
<p>The status groups are <code>passed</code> (원안가결, 수정가결, 대안반영폐기), <code>enacted</code> (원안가결, 수정가결), <code>reflected</code> (bills with <code>law_reflected</code> = 1), <code>pending</code> (계류중), <code>rejected</code> (부결, 폐기, 철회) and <code>expired</code> (임기만료폐기). A vetoed bill counts as enacted only if it was passed again.</p>
</section>
<section id="search-propose-reason-texts" class="level3">
<h3 class="anchored" data-anchor-id="search-propose-reason-texts">Search propose-reason texts</h3>
<p><code>search</code> queries bill <strong>titles</strong>. <code>text</code> searches within the full <strong>propose-reason text</strong> (제안이유) - the substantive rationale behind each bill.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find bills mentioning climate change in their rationale</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> text <span class="st">"기후변화"</span> <span class="at">--assembly</span> 22</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find bills discussing AI regulation rationale</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> text <span class="st">"인공지능 규제"</span> <span class="at">-n</span> 10</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This covers 60,925 member law bills of the 20th-22nd Assembly, 60,546 of them with a propose-reason text (99.4%). The 22nd stops with the bills proposed by 2026-02-27.</p>
</section>
</section>
<section id="bill-lifecycle-timeline" class="level2">
<h2 class="anchored" data-anchor-id="bill-lifecycle-timeline">Bill lifecycle timeline</h2>
<p>The “killer feature” of <code>kna</code> - see any bill’s full journey through the legislative process:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> show 2213549</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>약사법 일부개정법률안

  bill_no        2213549
  assembly       22nd
  kind           법률안
  proposer       남인순의원 등 13인
  committee      보건복지위원회
  status         수정가결

  LIFECYCLE               date    days
  ● 발의             2025-10-13       -
  ● 소관위 회부      2025-10-14      +1
  ● 소관위 상정      2025-11-12     +30
  ● 소관위 처리      2026-04-29    +198
  ● 법사위 회부      2026-04-29    +198
  ● 본회의 의결      2026-08-26    +317
  ● 공포             2026-09-22    +344

  VOTE   찬성 205 / 반대 1 / 기권 6 (재적 299)

  PROPOSE REASON
  현행법령은 의약품도매상 또는 의약품의 품목허가를 받은 자의 영업소로 오인하게
  할 우려가 있는 표시, ... (486 chars total)

  http://likms.assembly.go.kr/bill/billDetail.do?billId=PRC_B2C5A1A0Z1A0Y1Z0G2H2F2G6E9C4D1&amp;ageFrom=22&amp;ageTo=22</code></pre>
<p>Each stage shows:</p>
<ul>
<li><strong>●</strong> reached (with date and days since proposal)</li>
<li><strong>○</strong> not reached (bill did not advance to this stage)</li>
</ul>
<p>Lifecycle stages: 발의 → 소관위 회부 → 소관위 상정 → 소관위 처리 → 법사위 회부 → 본회의 의결 → 공포</p>
<p>A bill without a floor decision shows its final disposition in place of 본회의 의결, for example <code>처리 (대안반영폐기)</code> for a bill absorbed into a committee alternative. A vetoed bill adds the presidential reconsideration request and the re-vote, and its tally is that of the first passage:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> show 2200851</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>  status         수정가결
  vetoed         재의요구 after 수정가결
  ...
  ● 본회의 의결          2024-12-26    +185
  ● 재의요구             2025-01-22    +212
  ● 재의결 (수정가결)    2025-04-17    +297
  ● 공포                 2025-04-22    +302

  VOTE   찬성 161 / 반대 94 / 기권 6 (재적 300), first passage</code></pre>
</section>
<section id="legislator-profiles" class="level2">
<h2 class="anchored" data-anchor-id="legislator-profiles">Legislator profiles</h2>
<div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> legislator 이재명 <span class="at">--assembly</span> 22</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>  이재명 (IUD9392R) · 22nd Assembly
  ────────────────────────────────────────
  party                더불어민주당 (at election)
  district             인천 계양구을
  committee            외교통일위원회
  election             지역구 (재선 in the 22nd)
  ideal point          -0.360 (22nd, bridged W-NOMINATE, v20260917)
  rank                 153 / 305 in the 22nd (← 진보 ··· 보수 →)

  BILL RECORD (lead proposer, including joint leads)
  led                  4 bills
  enacted              0 (0.0%)
  promulgated          0
  alt-reflected        2
  median days          316d (proposal → processing)</code></pre>
<p>Shows:</p>
<ul>
<li><strong>Party at election</strong>, district and the committees served in that assembly</li>
<li><strong>Seniority at that assembly</strong> (초선, 재선, …), not the lifetime count</li>
<li>Bridged W-NOMINATE <strong>ideal point</strong> (ideological position) with its vintage</li>
<li><strong>Rank</strong> within the assembly (← liberal … conservative →)</li>
<li><strong>Bill record</strong>: bills led, enacted count and rate, promulgated count</li>
<li><strong>Top enacted bills</strong> with dates</li>
</ul>
<p>Names are matched exactly, and some legislators share a name. The 22nd Assembly has two members named 박지원, so the CLI lists both MONA_CDs and asks for one:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> legislator 박지원 <span class="at">--assembly</span> 22</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   2 legislators named 박지원 in the 22nd Assembly:</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   8BF5855P  22nd  더불어민주당  전남광주통합특별시 해남군완도군진도군</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   H7X3372O  22nd  더불어민주당  전북 군산시김제시부안군을</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Pick one by MONA_CD (the name is still required)</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> legislator 박지원 <span class="at">--assembly</span> 22 <span class="at">--mona</span> 8BF5855P</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Without --assembly, one row per term served</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> legislator 추미애</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ideal points are available for the 20th-22nd Assembly only (940 legislator-terms), because the API has member-level votes from the 20th on. For the 17th-19th, the bill record is shown without ideological positioning. The 22nd is in session, and 16 members seated during 2026 are missing from the vote API, so they have no 22nd ideal point yet.</p>
</div>
</div>
</section>
<section id="aggregate-statistics" class="level2">
<h2 class="anchored" data-anchor-id="aggregate-statistics">Aggregate statistics</h2>
<section id="legislative-funnel" class="level3">
<h3 class="anchored" data-anchor-id="legislative-funnel">Legislative funnel</h3>
<p>How many bills survive each stage of the legislative process?</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> stats funnel <span class="at">--assembly</span> 22</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>  22nd Assembly · Legislative Funnel (법률안 only)

  Stage           Bills     Rate
  발의           21,022   100.0%  ██████████████████████████████
  소관위 회부    20,966    99.7%  █████████████████████████████
  소관위 상정    17,687    84.1%  █████████████████████████
  소관위 처리     6,396    30.4%  █████████
  법사위 회부     1,729     8.2%  ██
  본회의 의결     1,673     8.0%  ██
  공포            1,555     7.4%  ██

  Each stage counts bills that reached it or a later stage.
  본회의 의결 = floor decision (원안가결, 수정가결, 부결); 공포 = promulgated.</code></pre>
<p>Counting each stage as “reached it or a later stage” keeps the funnel from widening when a bill skips a stage. Committee alternatives (위원장 대안) are never referred to a committee, and bills of the 법제사법위원회 itself skip the 법사위 review.</p>
</section>
<section id="passage-rate-trend" class="level3">
<h3 class="anchored" data-anchor-id="passage-rate-trend">Passage rate trend</h3>
<div class="sourceCode" id="cb17"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> stats passage-rate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>  Passage Rate Trend · 17-22nd Assembly (법률안 only)

  Assembly    Total   Passed    Rate   Enacted    Rate   Promul.    Rate
  17th        7,489    3,812   50.9%     1,913   25.5%     1,913   25.5%
  18th       13,913    6,178   44.4%     2,353   16.9%     2,353   16.9%
  19th       17,822    7,456   41.8%     2,793   15.7%     2,793   15.7%
  20th       24,141    8,758   36.3%     3,195   13.2%     3,195   13.2%
  21st       25,858    8,906   34.4%     2,959   11.4%     2,959   11.4%
  22nd       21,022    5,850   27.8%     1,644    7.8%     1,555    7.4%

  passed = 원안가결 + 수정가결 + 대안반영폐기
  enacted = 원안가결 + 수정가결 (final result: a vetoed bill counts only if re-passed)
  promulgated = promulgation date recorded (became law)</code></pre>
<p>The enacted rate declines from 25.5% (17th) to 11.4% (21st) - legislative inflation at work. The 22nd is still in session, so its 7.8% is not final.</p>
</section>
</section>
<section id="data-export" class="level2">
<h2 class="anchored" data-anchor-id="data-export">Data export</h2>
<p>Extract filtered subsets for downstream analysis in R, Stata, or Python:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Health committee bills, enacted only</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> export health.csv <span class="at">--assembly</span> 22 <span class="at">--committee</span> 보건복지 <span class="at">--status</span> enacted</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># All 22nd Assembly bills as Parquet</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> export all_22.parquet <span class="at">--assembly</span> 22</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># All law bills (법률안) across all assemblies</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="ex">kna</span> export laws.csv <span class="at">--kind</span> 법률안</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Format auto-detected from extension: <code>.csv</code>, <code>.parquet</code>, <code>.tsv</code>. <code>kna export</code> writes bills only, with all 67 master columns. To keep, say, government bills only, filter the export on <code>ppsr_kind == "정부"</code>.</p>
</section>
<section id="using-kna-data-in-python" class="level2">
<h2 class="anchored" data-anchor-id="using-kna-data-in-python">Using kna data in Python</h2>
<p>The <code>kna</code> package also works as a Python library:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> kna.data <span class="im">import</span> BillDB</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>db <span class="op">=</span> BillDB()  <span class="co"># reads KBL_DATA, or data/processed in a kna checkout</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load all 22nd Assembly bills</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>bills <span class="op">=</span> db.bills(assembly<span class="op">=</span><span class="dv">22</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(bills)<span class="sc">:,}</span><span class="ss"> bills, </span><span class="sc">{</span><span class="bu">len</span>(bills.columns)<span class="sc">}</span><span class="ss"> columns"</span>)  <span class="co"># 21,581 bills, 67 columns</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load with column pruning (fast)</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> db.bills(assembly<span class="op">=</span><span class="dv">22</span>, columns<span class="op">=</span>[<span class="st">"bill_id"</span>, <span class="st">"bill_nm"</span>, <span class="st">"status"</span>, <span class="st">"ppsl_dt"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"enacted"</span>, <span class="st">"promulgated"</span>, <span class="st">"vetoed"</span>])</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Ideal points: bridged W-NOMINATE by default, in the column ideal_point</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>ip <span class="op">=</span> db.ideal_points()  <span class="co"># 940 legislator-terms, positive = conservative</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>dw <span class="op">=</span> db.ideal_points(series<span class="op">=</span><span class="st">"dwnominate"</span>)  <span class="co"># or series="wnominate"</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Roll call votes (20th-22nd): party = party at election, party_api = API label</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>votes <span class="op">=</span> db.roll_calls(assembly<span class="op">=</span><span class="dv">22</span>)  <span class="co"># 545,107 member-level votes</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>tallies <span class="op">=</span> db.vote_events(assembly<span class="op">=</span><span class="dv">22</span>)  <span class="co"># 1,847 plenary tallies</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>vetoes <span class="op">=</span> db.veto_events()  <span class="co"># 47 presidential vetoes (재의요구)</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Bill texts</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>texts <span class="op">=</span> db.bill_texts()  <span class="co"># 60,925 propose-reason texts</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Member metadata (party at election, district, seniority at this assembly,</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="co"># committees served in this assembly, sex, birth date)</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>members <span class="op">=</span> db.members(assembly<span class="op">=</span><span class="dv">22</span>)  <span class="co"># 321 members</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>spells <span class="op">=</span> db.committee_assignments(assembly<span class="op">=</span><span class="dv">22</span>)  <span class="co"># 1,763 dated committee spells</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Cosponsorship: one row per bill and member, role 대표발의, 공동발의 or 찬성</span></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>edges <span class="op">=</span> db.cosponsorship_edges(assembly<span class="op">=</span><span class="dv">22</span>)  <span class="co"># 255,415 bill-member rows</span></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Asset disclosures (net_worth, real estate, stocks, etc. in 천원)</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>assets <span class="op">=</span> db.assets(assembly<span class="op">=</span><span class="dv">22</span>)  <span class="co"># 299 member-year wealth rows</span></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Committee meetings (lowercase columns in every assembly)</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>meetings <span class="op">=</span> db.committee_meetings(<span class="dv">22</span>)  <span class="co"># 137,152 records</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Pitfalls with kna 0.7.0
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>There is no <code>kna.load()</code>. Load every table through <code>BillDB</code>, or read the files in <code>data/processed/</code> directly.</li>
<li>Join legislators on MONA_CD, never on the name. It is <code>mona_cd</code> in the member tables and <code>member_id</code> in the roll calls, ideal points and cosponsorship edges. Same-name pairs exist in most assemblies, for example 박지원 in the 22nd.</li>
<li><code>reelection</code> is the lifetime count at the time of collection. For seniority at a given assembly (초선, 재선, …), use <code>term_number</code> or <code>seniority</code>.</li>
<li><code>party</code> is the party at election and keeps the satellite list parties, such as 더불어민주연합 and 국민의미래 in the 22nd. <code>party_current</code> gives the current party of serving 22nd members.</li>
<li><code>ideal_point</code> has positive values for conservatives. Do not flip its sign, as code written for the old <code>aligned</code> column did.</li>
</ul>
</div>
</div>
</section>
<section id="using-kna-data-in-r" class="level2">
<h2 class="anchored" data-anchor-id="using-kna-data-in-r">Using kna data in R</h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Paths are relative to the root of the kna checkout</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load master bills</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>master <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"data/processed/master_bills_22.parquet"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># All assemblies (the same 67 columns in every file)</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>all_bills <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(<span class="dv">17</span><span class="sc">:</span><span class="dv">22</span>, <span class="cf">function</span>(age)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_parquet</span>(<span class="fu">sprintf</span>(<span class="st">"data/processed/master_bills_%d.parquet"</span>, age)))</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Ideal points: bridged series, positive = conservative (no sign flip)</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>ip <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/processed/ideal_points_bridged.csv"</span>,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">member_id =</span> <span class="fu">col_character</span>())) <span class="sc">%&gt;%</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">ideal_point =</span> bridged_1d)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Members, with seniority at this assembly (term_number 1 = 초선)</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>members <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"data/processed/members_22.parquet"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">first_term =</span> term_number <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Bill texts</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>texts <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"data/processed/bill_texts_linked.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="command-reference" class="level2">
<h2 class="anchored" data-anchor-id="command-reference">Command reference</h2>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Command</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>kna info</code></td>
<td>Database overview</td>
</tr>
<tr class="even">
<td><code>kna search KEYWORD</code></td>
<td>Search bill titles</td>
</tr>
<tr class="odd">
<td><code>kna text KEYWORD</code></td>
<td>Search propose-reason texts</td>
</tr>
<tr class="even">
<td><code>kna show BILL_NO</code></td>
<td>Bill detail + lifecycle timeline</td>
</tr>
<tr class="odd">
<td><code>kna legislator NAME</code></td>
<td>Legislator profile + ideal point (<code>--mona</code> for shared names)</td>
</tr>
<tr class="even">
<td><code>kna stats funnel</code></td>
<td>Legislative funnel</td>
</tr>
<tr class="odd">
<td><code>kna stats passage-rate</code></td>
<td>Cross-assembly passage rates</td>
</tr>
<tr class="even">
<td><code>kna export PATH</code></td>
<td>Export filtered bills to CSV/Parquet</td>
</tr>
</tbody>
</table>
</section>
<section id="companion-data" class="level2">
<h2 class="anchored" data-anchor-id="companion-data">Companion data</h2>
<p>For hearing and audit transcripts (15.1M speaker turns), see the companion dataset:</p>
<ul>
<li><a href="https://github.com/kyusik-yang/kr-hearings-data">kr-hearings-data</a> - Korean National Assembly hearing transcripts (2000-2026)</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Built with <a href="https://quarto.org">Quarto</a> · Data from <a href="https://open.assembly.go.kr">열린국회정보</a></div>   
    <div class="nav-footer-right">Kyusik Yang · NYU Department of Politics</div>
  </div>
</footer>



</body></html>